export const featuredArtists = [
  {
    id: 2,
    name: "Luna Rivers",
    genre: "Indie Pop",
    country: "USA",
    followers: 284000,
    image: "/images/luna_rivers.jpeg",
    banner: "/banners/luna_rivers.jpeg",
    description:
      "Known for her dreamy vocals and celestial melodies, Luna Rivers has become a rising indie-pop star with emotionally charged performances.",
    nextEvent: {
      title: "Moonlight Festival",
      date: "2025-10-20",
      venue: "Los Angeles, USA",
    },
  },
  {
    id: 1,
    name: "Rapture",
    genre: "DHH",
    country: "India",
    followers: 456000,
    image: "/images/rapture.jpeg",
    banner: "/banners/rapture.jpeg",
    description:
      "Blending Indian tunes with modern pop and electronic beats, Rapture is known for redefining DHH Fusion on stage.",
    nextEvent: {
      title: "Rhythm of the East",
      date: "2025-11-12",
      venue: "Mumbai, India",
    },
  },
  {
    id: 3,
    name: "Selena Gomez",
    genre: "Pop",
    country: "USA",
    followers: 512000,
    image: "/images/selena.jpeg",
    banner: "/banners/selena.jpeg",
    description:
      "Selena Gomez is a multi-talented artist with over 43 million monthly listeners on Spotify, where her music career has yielded numerous chart-topping hits and several billion-streamed songs",
    nextEvent: {
      title: "Eclipse Nights",
      date: "2025-12-05",
      venue: "NYC, USA",
    },
  },
];

export const artists = [
  {
    id: 1,
    name: "Luna Rivers",
    genre: "Indie Pop",
    country: "USA",
    followers: 284000,
    image: "/images/luna_rivers.svg",
    latestShow: "Moonlight Festival, Los Angeles, USA",
  },
  {
    id: 2,
    name: "Arjun Dev",
    genre: "Bollywood Fusion",
    country: "India",
    followers: 456000,
    image: "/images/arjun_dev.svg",
    latestShow: "Rhythm of the East, Mumbai, India",
  },
  {
    id: 3,
    name: "Nova Reed",
    genre: "Electronic",
    country: "UK",
    followers: 512000,
    image: "/images/nova_reed.svg",
    latestShow: "Eclipse Nights, London, UK",
  },
  {
    id: 4,
    name: "Sakura Aoki",
    genre: "J-Pop",
    country: "Japan",
    followers: 378000,
    image: "/images/sakura_aoki.svg",
    latestShow: "Tokyo Beats, Shibuya, Japan",
  },
  {
    id: 5,
    name: "Leo Alvarez",
    genre: "Latin Pop",
    country: "Spain",
    followers: 421000,
    image: "/images/leo_alvarez.svg",
    latestShow: "Fiesta Nights, Madrid, Spain",
  },
  {
    id: 6,
    name: "Mila Storm",
    genre: "Alternative Rock",
    country: "Australia",
    followers: 189000,
    image: "/images/mila_storm.svg",
    latestShow: "Waves Fest, Sydney, Australia",
  },
  {
    id: 7,
    name: "Ethan Cole",
    genre: "Jazz",
    country: "USA",
    followers: 96000,
    image: "/images/ethan_cole.svg",
    latestShow: "Blue Note Sessions, New York, USA",
  },
  {
    id: 8,
    name: "Zara Noor",
    genre: "Soul",
    country: "Pakistan",
    followers: 154000,
    image: "/images/zara_noor.svg",
    latestShow: "Soulful Evenings, Lahore, Pakistan",
  },
  {
    id: 9,
    name: "Elena Cruz",
    genre: "R&B",
    country: "Brazil",
    followers: 249000,
    image: "/images/elena_cruz.svg",
    latestShow: "Midnight Groove, São Paulo, Brazil",
  },
  {
    id: 10,
    name: "The Astral Collective",
    genre: "Psychedelic Rock",
    country: "Germany",
    followers: 312000,
    image: "/images/astral_collective.svg",
    latestShow: "Dreamscapes Festival, Berlin, Germany",
  },
];

export const events = [
  {
    id: 101,
    artistId: 1,
    title: "Moonlight Festival",
    date: "2025-10-20",
    venue: "Los Angeles, USA",
  },
  {
    id: 102,
    artistId: 2,
    title: "Rhythm of the East",
    date: "2025-11-12",
    venue: "Mumbai, India",
  },
  {
    id: 103,
    artistId: 3,
    title: "Eclipse Nights",
    date: "2025-12-05",
    venue: "London, UK",
  },
  {
    id: 104,
    artistId: 4,
    title: "Tokyo Beats",
    date: "2025-11-25",
    venue: "Shibuya, Japan",
  },
  {
    id: 105,
    artistId: 5,
    title: "Fiesta Nights",
    date: "2025-12-18",
    venue: "Madrid, Spain",
  },
];

export const filters = {
  genres: [
    "Indie Pop",
    "Bollywood Fusion",
    "Electronic",
    "J-Pop",
    "Latin Pop",
    "Alternative Rock",
    "Jazz",
    "Soul",
    "R&B",
    "Psychedelic Rock",
  ],
  countries: [
    "USA",
    "India",
    "UK",
    "Japan",
    "Spain",
    "Australia",
    "Pakistan",
    "Brazil",
    "Germany",
  ],
};
